// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0PFPMCNBXVKgpCdof3YrFYAfMUJCGHWo',
    appId: '1:842460995990:web:46b98abf7f24c500573db7',
    messagingSenderId: '842460995990',
    projectId: 'apkaiapp',
    authDomain: 'apkaiapp.firebaseapp.com',
    storageBucket: 'apkaiapp.firebasestorage.app',
    measurementId: 'G-13F76C6LY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAb4rGnVYLqbJRxmoYlzsRV60JFa469QY',
    appId: '1:842460995990:android:fca8a2bdd8753763573db7',
    messagingSenderId: '842460995990',
    projectId: 'apkaiapp',
    storageBucket: 'apkaiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06dVB-w0AKfPSe9MGFczNW0EMk29T3zE',
    appId: '1:842460995990:ios:4293f8b7b3f6305b573db7',
    messagingSenderId: '842460995990',
    projectId: 'apkaiapp',
    storageBucket: 'apkaiapp.firebasestorage.app',
    iosBundleId: 'com.example.apkAiCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06dVB-w0AKfPSe9MGFczNW0EMk29T3zE',
    appId: '1:842460995990:ios:4293f8b7b3f6305b573db7',
    messagingSenderId: '842460995990',
    projectId: 'apkaiapp',
    storageBucket: 'apkaiapp.firebasestorage.app',
    iosBundleId: 'com.example.apkAiCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0PFPMCNBXVKgpCdof3YrFYAfMUJCGHWo',
    appId: '1:842460995990:web:c92e8d6c13a8c052573db7',
    messagingSenderId: '842460995990',
    projectId: 'apkaiapp',
    authDomain: 'apkaiapp.firebaseapp.com',
    storageBucket: 'apkaiapp.firebasestorage.app',
    measurementId: 'G-26VGSXVCQ3',
  );
}
